### PR TITLE
Add C# Bindings

### PR DESCRIPTION
**Pull request by marv7000**
Adds memory-safe and type-safe C# bindings through P/Invoke.

### CODE REVIEW

**Comment by thkukuk** [comment]
Beside the failing test, which should be fixed, some kind of documentation, at mentioning it in README.md, would be nice.

**Comment by marv7000** [comment]
I added documentation and mentioned the Python and C# bindings in the README. As for the test, I'm not sure why it's failing since it doesn't cover any bindings.

**Comment by schubi2** [comment]
> I added documentation and mentioned the Python and C# bindings in the README. As for the test, I'm not sure why it's failing since it doesn't cover any bindings.

Hm, I do not see any failing testcase. So we are merging it and fix them if it is failing again.

**Comment by marv7000** [comment]
Some test on my first commit was failing, but the error was unrelated to my changes so I'm assuming it's just a temporary issue.

**Pull request merged**
